id: P13622543
initial_creation_type: input
source_metadata:
  title: Pewar Rinpoche
  language: en
  description: 'Texts by and about Pewar Rinpoche Chime Dorje (dpe war ''chi med rdo
    rje, b. 1933), a major contributor to the recent resurgence of Buddhism in Tibet:'
  volume:
    9141aa13f56c4b36a2a6a8b495eed5c8:
      title: Prayer for the Long Life of Pewar Rinpoche
      parent: Long Life Prayers
created_at: '2022-03-01T01:17:56.077661'
last_modified_at: '2022-03-01T01:17:56.077667'
